version: '3'

services:
  db:
    build: database container
    container_name: db
    volumes:
      - ./database container/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=jaeQuu7ziweeci5e
      - PGPORT=6666
    ports:
      - "6666:6666"

  app:
    build: server container
    container_name: app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://app_user:jaeQuu7ziweeci5e@db:6666/app_db
    ports:
      - "8080:8080"
      - "9999:9999"

  frontend:
    build: web_front_container
    container_name: web_frontend
    depends_on:
      - app
    ports:
      - "80:80"