version: '3.8'

services:
  db:
    build: database container
    container_name: db
    volumes:
      - ./database container/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=bibki1
    ports:
      - "6666:6666"

  app:
    build: server container
    container_name: app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://app_user:bibki1@db:5432/app_db
    ports:
      - "8080:8080"